#!/bin/sh

### BEGIN INIT INFO
# Provides:        ntp
# Required-Start:  $network $remote_fs $syslog
# Required-Stop:   $network $remote_fs $syslog
# Default-Start:   2 3 4 5
# Default-Stop:    1
# Short-Description: Start NTP daemon
### END INIT INFO

#echo "We are: $0 : $1"

if [ -f /etc/safe_mode ]; then
exit 0
fi

DAEMON=/usr/bin/Demetro/Demetro

test -x $DAEMON || exit 5

case $1 in
	start)
		echo "Starting Demetro"
		cd /usr/bin/Demetro
  		start-stop-daemon --start --quiet --oknodo --pidfile $PIDFILE --startas $DAEMON --
		$DAEMON &
  		;;
	stop)
		echo "Stopping Demetro"
		killall Demetro
  		;;
	restart|force-reload)
		$0 stop && sleep 2 && $0 start
  		;;
	try-restart)
		if $0 status >/dev/null; then
			$0 restart
		else
			exit 0
		fi
		;;
	reload)
		exit 3
		;;
	status)
		status_of_proc $DAEMON "Demetro"
		;;
	*)
		echo "Usage: $0 {start|stop|restart|try-restart|force-reload|status}"
		exit 2
		;;
esac
