#!/bin/sh
#
# Start the network....
#

#echo "We are: $0 : $1"

if [ -f /etc/safe_mode ]; then
exit 0
fi

case "$1" in
  start)
 	echo "Starting network..."
	/sbin/ifup -a
	;;
  stop)
	echo -n "Stopping network..."
	/sbin/ifdown -a
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

