#!/bin/sh


# Start all init scripts in /etc/init.d
# executing them in numerical order.
#

#echo "Start rcS "

PATH=/sbin:/bin:/usr/sbin:/usr/bin
runlevel=S
prevlevel=N
umask 022
export PATH runlevel prevlevel

#	Make sure proc is mounted
#
[ -d "/proc/1" ] || mount /proc

#
#	Source defaults.
#
. /etc/default/rcS

echo "TMPTIME= $TMPTIME $RUNLEVEL"

#
#	Trap CTRL-C &c only in this shell so we can interrupt subprocesses.
#
trap ":" INT QUIT TSTP

#
#	Call all parts in order.
#
. /etc/init.d/rc S

#proc::sysinit:/bin/mount -t proc proc /proc
#rwmo::sysinit:/bin/mount -o remount,rw / # REMOUNT_ROOTFS_RW
#dpts::sysinit:/bin/mkdir -p /dev/pts
#dshm::sysinit:/bin/mkdir -p /dev/shm
#moun::sysinit:/bin/mount -a
#host::sysinit:/bin/hostname -F /etc/hostname
#init::sysinit:/etc/init.d/rcS


